### ISSUE TITLE
Lägg till setup.py för automatisk installation av dependencies

### ISSUE THREAD

**Issue by Frojdholm** [kirajcg/pyscbwrapper#2]
Med en setup.py slipper man själv installera requests.

**Comment by rickardlofberg** [comment]
Kul att se att det redan finns en PR för detta då jag stötte på samma problem.
För att återskapa problemet :
1. Skapa en ny python miljö: `python -m venv .venv`
2. Aktivera miljön: `. ./.venv/bin/activate`
3. Installera paketet: `pip install pyscbwrapper`
4. Starta python och försök importera paketet
`python -i`
`>>> from pyscbwrapper import SCB`

Vilket ger: `ModuleNotFoundError: No module named 'requests'`

@kirajcg Hoppas vi kan få PR:n mergad.
